import type { Transcript } from "@/lib/transcript";

/**
 * Generated by `node scripts/import-subtitles.mjs` from `subtitles/en.srt`
 * or `subtitles/en.vtt`. Do not edit by hand; re-run the import.
 */
export const transcriptEn: Transcript = [];
