import type { Transcript } from "@/lib/transcript";

/**
 * Generated by `node scripts/import-subtitles.mjs` from `subtitles/fr.srt`
 * or `subtitles/fr.vtt`. Do not edit by hand; re-run the import.
 */
export const transcriptFr: Transcript = [];
