import type { Transcript } from "@/lib/transcript";

/**
 * Generated by `node scripts/import-subtitles.mjs` from `subtitles/ja.srt`
 * or `subtitles/ja.vtt`. Do not edit by hand; re-run the import.
 */
export const transcriptJa: Transcript = [];
