import type { Transcript } from "@/lib/transcript";

/**
 * Generated by `node scripts/import-subtitles.mjs` from `subtitles/ko.srt`
 * or `subtitles/ko.vtt`. Do not edit by hand; re-run the import.
 */
export const transcriptKo: Transcript = [];
