import type { VisionArticle } from "@/lib/vision-article";

export const visionArticleEn: VisionArticle = {
  byline:
    "By Frank Houbre, vision, process, and why AI is a bridge, not a shortcut.",
  sections: [
    {
      paragraphs: [
        "My name is Frank Houbre, and Lost Garden is an original anime project I'm creating with the help of artificial intelligence.",
        "At its heart, Lost Garden is a dark fantasy story about Sol, an empty suit of armor with a lantern-shaped helmet, and Rose, a mysterious child connected to the rebirth of a wounded world. The story takes place in a vast underground universe filled with blue forests, glowing mushrooms, giant roots, strange machines, ancient caverns, silent pilgrims, and forgotten beings that seem older than memory.",
        "It is a poetic, emotional series. I want it to feel mysterious, beautiful, dangerous, and deeply human, even if one of the main characters is literally an empty armor.",
        "I've always loved stories that stay with you long after you finish them. Made in Abyss marked me with its sense of wonder, danger, and lost innocence. Attack on Titan impressed me with its scale, mystery, tragedy, and the way it slowly reveals the true nature of its world. With Lost Garden, I'm not trying to copy those works. I'm trying to create something that carries the same kind of emotional weight. A story that feels vast, strange, and painful, but also tender.",
        "And for the first time, thanks to AI, I can actually try to build it.",
      ],
    },
    {
      heading: "AI did not give me the story. It helped me make the story visible.",
      paragraphs: [
        "One thing I want to make clear is that AI is not \"making the anime for me\" in some magical one-click way.",
        "The idea, the characters, the emotional direction, the world, the tone, the story choices, the relationship between Sol and Rose, all of that comes from human intention. AI helps me turn those ideas into images, scenes, animation tests, music directions, and production material much faster than would have been possible before.",
        "For Lost Garden, the process starts with the same thing any animated project needs: a clear vision.",
      ],
      list: [
        "Who is the story about?",
        "What does the world feel like?",
        "What is the emotional promise?",
        "What should the viewer feel in the first minute?",
        "What should they remember after the episode ends?",
      ],
      trailingParagraphs: [
        "AI is powerful, but without a clear artistic direction, it becomes random. The more precise the world becomes, the better the results become.",
      ],
    },
    {
      heading: "Character sheets are the foundation",
      paragraphs: [
        "One of the most important parts of the process is creating character sheets.",
        "For Sol, I needed a design that was instantly recognizable: an old hollow armor, a lantern-shaped helmet, no real face, no body inside, modest proportions, a fragile and slightly awkward attitude. He is not a powerful legendary knight. He is damaged, poetic, clumsy, and protective.",
        "For Rose, I needed the opposite energy: a small child, soft, innocent, calm, with a quiet emotional strength. She needed to feel like someone the world wants to use, but also someone who must be protected simply because she is a child.",
        "The character sheets help keep the characters consistent from scene to scene. Front view, side view, close-ups, attitude references, costume references, emotional references. Without that, an AI-generated anime can quickly become inconsistent. Faces shift, costumes change, proportions drift.",
        "Character sheets are not just pretty images. They are production tools.",
        "They allow the character to exist across many scenes.",
      ],
    },
    {
      heading: "The world needs its own visual bible",
      paragraphs: [
        "The same thing applies to the environments.",
        "At first, Lost Garden had elements like a cathedral and a more traditional outside world. But the more the project evolved, the more I realized the strongest identity was underground.",
        "So the world became a network of immense ancient caverns.",
      ],
      list: [
        "Blue forests.",
        "Cyan mist.",
        "Glowing mushrooms.",
        "White lilies.",
        "Giant roots.",
        "Floating stone platforms.",
        "Underground rivers.",
        "Sleeping alien machines covered in moss.",
        "Silent masked pilgrims carrying gongs across stone bridges.",
        "A Source Tree so huge it feels like a living goddess.",
      ],
      trailingParagraphs: [
        "This visual bible is essential. It prevents the project from becoming a mix of random fantasy images. Every prompt, every scene, every environment has to come back to the same identity.",
      ],
      callouts: [
        "The goal is not \"cool fantasy.\"",
        "The goal is Lost Garden.",
        "A world that feels beautiful but wounded.",
        "Soft but dangerous.",
        "Sacred, but not religious.",
        "Anime, but not generic.",
      ],
    },
    {
      heading: "AI animation makes independent anime possible",
      paragraphs: [
        "The most exciting part is animation.",
        "With tools like Seedance 2 and other AI video models, it becomes possible to create short animated sequences from carefully designed prompts and reference images.",
        "For Lost Garden, I can create scenes like:",
      ],
      list: [
        "Sol waking up on a stone altar in a blue cavern.",
        "Sol discovering that he is empty inside.",
        "A gigantic alien eye opening beneath him.",
        "Masked pilgrims turning toward him all at once.",
        "Rose standing on a hill of white lilies in a dream.",
        "The Source Tree lifting Sol gently into her hand.",
        "A giant rose blooming from the earth and giving birth to a Source Child.",
      ],
      trailingParagraphs: [
        "These are scenes that, a few years ago, would have required a large animation team, a studio pipeline, and a lot of money just to prototype.",
        "Now, a creator with a strong idea can start building visual sequences alone or with a very small team.",
        "That does not mean it is easy.",
        "AI animation still requires direction. You need to think about camera angles, staging, continuity, silhouettes, movement, emotional beats, sound, and rhythm. A weak prompt gives a weak scene. A confused world gives confused visuals.",
        "But the barrier has changed.",
        "The question is no longer only: \"Can I afford to make this?\"",
        "It becomes: \"Can I direct this clearly enough?\"",
      ],
    },
    {
      heading: "Music and sound are part of the soul",
      paragraphs: [
        "For Lost Garden, part of the music and sound direction is also being explored with AI.",
        "The project needs a very specific sound: mystical, fragile, underground, emotional, sometimes science-fiction, sometimes sacred, but never generic trailer music.",
        "For example, when Sol meets the Source Tree, the music should not be heroic. It should feel ancient and overwhelming. Soft glass tones, low cello, wordless choir textures, cavern reverb, wooden root creaks, faint metallic armor resonance.",
        "When an alien machine wakes, the sound should become more sci-fi: cold drones, electric crackles, mechanical groans, alarm-like tones, and a signature alien cry.",
        "Even Sol himself has a sound identity. He does not have a real human voice. He makes hollow masculine metallic armor sounds: creaks, empty breaths, internal resonances, small grunts of frustration, strange metallic sighs.",
        "That kind of detail matters. Sound is not decoration. It tells the viewer what a character is before they fully understand it.",
      ],
    },
    {
      heading: "AI does not replace taste",
      paragraphs: [
        "I think this is the most important point.",
        "AI gives access. It gives speed. It gives power. But it does not replace taste.",
        "It does not decide what is moving.",
        "It does not know when a scene is too fast.",
        "It does not know when a reveal is too early.",
        "It does not know if a character relationship feels true.",
        "It does not know if the audience needs silence instead of spectacle.",
        "That remains the job of the creator.",
        "With Lost Garden, I spend a lot of time refining the tone. Sometimes a scene becomes too explanatory, so I remove dialogue. Sometimes an image is beautiful but not coherent with the world, so I change the bible. Sometimes an action scene works, but the emotional rhythm is too fast, so I slow down.",
        "AI can generate, but the creator must choose.",
        "And choosing is the real work.",
      ],
    },
    {
      heading: "Why this matters",
      paragraphs: [
        "I believe AI is opening a door for a new generation of creators.",
        "There are people everywhere with powerful stories in their heads. People who love anime, cinema, manga, fantasy, horror, science fiction, emotional storytelling. People who have ideas, but never had the budget, the studio, the team, or the technical access to bring them to life.",
        "AI does not remove the need for craft.",
        "It does not make everyone a great director automatically.",
        "But it gives people a chance to try.",
        "And that is huge.",
        "A person with a strong idea can now create character sheets, visual concepts, music tests, animated scenes, trailers, pitch materials, and maybe even full episodes. Not perfectly. Not instantly. But enough to begin.",
        "That beginning matters.",
        "Because many projects die before they are ever seen.",
      ],
    },
    {
      heading: "My hope for Lost Garden",
      paragraphs: [
        "With Lost Garden, I want to make a series that feels touching.",
        "Not just visually impressive.",
        "Not just \"made with AI.\"",
        "Not just a technical demonstration.",
        "I want people to care about Sol and Rose.",
        "I want them to feel the loneliness of an empty armor trying to understand why it exists. I want them to feel the tenderness of a child who brings life back to a dying world. I want them to feel that strange mixture of wonder and fear when the blue forest opens into a giant cavern and something ancient starts moving in the mist.",
        "If AI allows me to make that emotion visible, then it becomes more than a tool. It becomes a bridge between imagination and production.",
        "That is what excites me the most.",
        "Not the idea that AI will replace artists.",
        "The idea that it can help more people become storytellers.",
      ],
    },
    {
      heading: "A message to creators",
      paragraphs: [
        "If you have a story in your head, start.",
        "Start with a character.",
        "Start with one image.",
        "Start with a scene.",
        "Start with a world bible.",
        "Start with a single emotional moment that you cannot stop thinking about.",
        "You do not need to know everything at the beginning. Lost Garden itself changed a lot while I was building it. The world became clearer scene after scene. The characters became stronger because I kept testing them, seeing them, refining them.",
        "AI makes iteration possible at a speed we have never had before.",
        "And maybe that is the real revolution.",
        "Not that machines create stories for us.",
        "But that people who were never allowed into the old production system can finally try to bring their worlds to life.",
        "Lost Garden is my attempt.",
        "A hollow knight.",
        "A child named Rose.",
        "A blue forest beneath the world.",
        "And somewhere in the dark, an ancient eye opening.",
        "I hope it inspires others to create theirs.",
      ],
    },
  ],
};
