import type { VisionArticle } from "@/lib/vision-article";

export const visionArticleFr: VisionArticle = {
  byline:
    "Par Frank Houbre : vision, processus, et pourquoi l'IA est un pont, pas un raccourci.",
  sections: [
    {
      paragraphs: [
        "Je m'appelle Frank Houbre, et Lost Garden est un projet d'anime original que je crée avec l'aide de l'intelligence artificielle.",
        "Au fond, Lost Garden est une dark fantasy poétique sur Sol, une armure vide au casque en forme de lanterne, et Rose, une enfant mystérieuse liée à la renaissance d'un monde blessé. L'histoire se déroule dans un vaste univers souterrain : forêts bleues, champignons lumineux, racines géantes, machines étranges, cavernes anciennes, pèlerins silencieux, et des êtres oubliés qui semblent plus vieux que la mémoire.",
        "C'est une série poétique et émotionnelle. Je veux qu'elle soit mystérieuse, belle, dangereuse et profondément humaine, même si l'un des personnages principaux est littéralement une armure vide.",
        "J'ai toujours aimé les histoires qui restent longtemps après la fin. Made in Abyss m'a marqué par son émerveillement, son danger et sa innocence perdue. L'Attaque des Titans m'a impressionné par son échelle, son mystère, sa tragédie, et la façon dont il révèle peu à peu la vraie nature de son monde. Avec Lost Garden, je ne cherche pas à copier ces œuvres. Je cherche à créer quelque chose qui porte le même poids émotionnel. Une histoire vaste, étrange et douloureuse, mais aussi tendre.",
        "Et pour la première fois, grâce à l'IA, je peux vraiment essayer de la construire.",
      ],
    },
    {
      heading:
        "L'IA ne m'a pas donné l'histoire. Elle m'a aidé à la rendre visible.",
      paragraphs: [
        "Je veux être clair : l'IA ne « fait pas l'anime à ma place » d'un simple clic magique.",
        "L'idée, les personnages, la direction émotionnelle, le monde, le ton, les choix narratifs, la relation entre Sol et Rose, tout cela vient d'une intention humaine. L'IA m'aide à transformer ces idées en images, scènes, tests d'animation, directions musicales et matériel de production bien plus vite qu'auparavant.",
        "Pour Lost Garden, le processus commence comme pour tout projet animé : une vision claire.",
      ],
      list: [
        "De qui parle l'histoire ?",
        "Quelle sensation donne le monde ?",
        "Quelle promesse émotionnelle ?",
        "Que doit ressentir le spectateur dans la première minute ?",
        "Que doit-il retenir après l'épisode ?",
      ],
      trailingParagraphs: [
        "L'IA est puissante, mais sans direction artistique claire, elle devient aléatoire. Plus le monde est précis, meilleurs sont les résultats.",
      ],
    },
    {
      heading: "Les fiches personnages sont le socle",
      paragraphs: [
        "L'une des étapes les plus importantes est la création des character sheets.",
        "Pour Sol, il me fallait un design immédiatement reconnaissable : une vieille armure creuse, un casque en lanterne, pas de vrai visage, pas de corps à l'intérieur, des proportions modestes, une attitude fragile et un peu maladroite. Ce n'est pas un chevalier légendaire tout-puissant. Il est abîmé, poétique, maladroit et protecteur.",
        "Pour Rose, l'énergie inverse : une petite fille, douce, innocente, calme, avec une force émotionnelle discrète. Elle devait donner l'impression d'être utilisée par le monde, tout en étant protégée simplement parce qu'elle est une enfant.",
        "Les fiches aident à garder les personnages cohérents d'une scène à l'autre. Face, profil, gros plans, attitudes, costumes, références émotionnelles. Sans cela, un anime généré par IA devient vite incohérent. Les visages changent, les costumes aussi, les proportions dérivent.",
        "Les character sheets ne sont pas que de jolies images. Ce sont des outils de production.",
        "Ils permettent au personnage d'exister sur de nombreuses scènes.",
      ],
    },
    {
      heading: "Le monde a besoin de sa propre bible visuelle",
      paragraphs: [
        "La même logique s'applique aux décors.",
        "Au début, Lost Garden avait une cathédrale et un monde extérieur plus classique. Mais plus le projet avançait, plus l'identité la plus forte était souterraine.",
        "Le monde est devenu un réseau de cavernes anciennes immenses.",
      ],
      list: [
        "Forêts bleues.",
        "Brume cyan.",
        "Champignons lumineux.",
        "Lys blancs.",
        "Racines géantes.",
        "Plateformes de pierre flottantes.",
        "Rivières souterraines.",
        "Machines extraterrestres endormies, couvertes de mousse.",
        "Pèlerins masqués et silencieux portant des gongs sur des ponts de pierre.",
        "Un Arbre Source si immense qu'il ressemble à une déesse vivante.",
      ],
      trailingParagraphs: [
        "Cette bible visuelle est essentielle. Elle empêche le projet de devenir un mélange d'images fantasy au hasard. Chaque prompt, chaque scène, chaque décor doit revenir à la même identité.",
      ],
      callouts: [
        "Le but n'est pas la « fantasy cool ».",
        "Le but, c'est Lost Garden.",
        "Un monde beau mais blessé.",
        "Doux mais dangereux.",
        "Sacré, sans être religieux.",
        "De l'anime, sans être générique.",
      ],
    },
    {
      heading: "L'animation par IA rend l'anime indépendant possible",
      paragraphs: [
        "La partie la plus excitante, c'est l'animation.",
        "Avec des outils comme Seedance 2 et d'autres modèles vidéo IA, on peut créer de courtes séquences animées à partir de prompts soignés et d'images de référence.",
        "Pour Lost Garden, je peux créer des scènes comme :",
      ],
      list: [
        "Sol qui se réveille sur un autel de pierre dans une caverne bleue.",
        "Sol découvrant qu'il est vide à l'intérieur.",
        "Un œil extraterrestre géant qui s'ouvre sous lui.",
        "Des pèlerins masqués qui se tournent vers lui d'un seul mouvement.",
        "Rose debout sur une colline de lys blancs dans un rêve.",
        "L'Arbre Source qui soulève Sol doucement dans sa main.",
        "Une rose géante qui fleurit de la terre et donne naissance à un Enfant Source.",
      ],
      trailingParagraphs: [
        "Il y a quelques années, ces scènes auraient exigé une grande équipe d'animation, un pipeline de studio et beaucoup d'argent rien que pour un prototype.",
        "Aujourd'hui, un créateur avec une idée forte peut commencer à construire des séquences visuelles seul ou avec une très petite équipe.",
        "Cela ne veut pas dire que c'est facile.",
        "L'animation IA demande toujours de la direction. Il faut penser aux angles de caméra, à la mise en scène, à la continuité, aux silhouettes, au mouvement, aux temps forts émotionnels, au son et au rythme. Un prompt faible donne une scène faible. Un monde confus donne des images confuses.",
        "Mais la barrière a changé.",
        "La question n'est plus seulement : « Est-ce que j'ai les moyens de le faire ? »",
        "Elle devient : « Est-ce que je sais le diriger assez clairement ? »",
      ],
    },
    {
      heading: "La musique et le son font partie de l'âme",
      paragraphs: [
        "Pour Lost Garden, une partie de la direction musicale et sonore est aussi explorée avec l'IA.",
        "Le projet a besoin d'un son très précis : mystique, fragile, souterrain, émotionnel, parfois science-fiction, parfois sacré, mais jamais une musique de bande-annonce générique.",
        "Par exemple, quand Sol rencontre l'Arbre Source, la musique ne doit pas être héroïque. Elle doit sembler ancienne et écrasante. Sons de verre doux, violoncelle grave, chœurs sans paroles, réverbération de caverne, craquements de racines de bois, faible résonance métallique d'armure.",
        "Quand une machine extraterrestre se réveille, le son devient plus sci-fi : drones froids, crépitements électriques, grognements mécaniques, tonalités d'alarme, et un cri alien signature.",
        "Sol lui-même a une identité sonore. Il n'a pas de vraie voix humaine. Il produit des sons d'armure métallique masculine et creuse : craquements, souffles vides, résonances internes, petits grognements de frustration, soupirs métalliques étranges.",
        "Ce genre de détail compte. Le son n'est pas une décoration. Il dit au spectateur ce qu'est un personnage avant qu'il le comprenne vraiment.",
      ],
    },
    {
      heading: "L'IA ne remplace pas le goût",
      paragraphs: [
        "Je pense que c'est le point le plus important.",
        "L'IA donne l'accès. Elle donne de la vitesse. Elle donne de la puissance. Mais elle ne remplace pas le goût.",
        "Elle ne décide pas de ce qui émeut.",
        "Elle ne sait pas quand une scène est trop rapide.",
        "Elle ne sait pas quand une révélation arrive trop tôt.",
        "Elle ne sait pas si une relation entre personnages sonne vrai.",
        "Elle ne sait pas si le public a besoin de silence plutôt que de spectacle.",
        "Cela reste le travail du créateur.",
        "Avec Lost Garden, je passe beaucoup de temps à affiner le ton. Parfois une scène devient trop explicative, alors j'enlève du dialogue. Parfois une image est belle mais incohérente avec le monde, alors je modifie la bible. Parfois une scène d'action fonctionne, mais le rythme émotionnel est trop rapide, alors je ralentis.",
        "L'IA peut générer, mais le créateur doit choisir.",
        "Et choisir, c'est le vrai travail.",
      ],
    },
    {
      heading: "Pourquoi c'est important",
      paragraphs: [
        "Je crois que l'IA ouvre une porte pour une nouvelle génération de créateurs.",
        "Partout, des gens ont des histoires puissantes dans la tête. Des gens qui aiment l'anime, le cinéma, le manga, la fantasy, l'horreur, la science-fiction, le récit émotionnel. Des gens qui ont des idées, mais n'ont jamais eu le budget, le studio, l'équipe ou l'accès technique pour les concrétiser.",
        "L'IA ne supprime pas le besoin de savoir-faire.",
        "Elle ne fait pas de tout le monde un grand réalisateur automatiquement.",
        "Mais elle donne une chance d'essayer.",
        "Et c'est énorme.",
        "Une personne avec une idée forte peut aujourd'hui créer des character sheets, des concepts visuels, des tests musicaux, des scènes animées, des bandes-annonces, du matériel de pitch, et peut-être même des épisodes entiers. Pas parfaitement. Pas instantanément. Mais assez pour commencer.",
        "Ce début compte.",
        "Parce que beaucoup de projets meurent avant d'être vus.",
      ],
    },
    {
      heading: "Mon espoir pour Lost Garden",
      paragraphs: [
        "Avec Lost Garden, je veux faire une série qui touche.",
        "Pas seulement visuellement impressionnante.",
        "Pas seulement « faite avec l'IA ».",
        "Pas seulement une démonstration technique.",
        "Je veux que les gens s'attachent à Sol et Rose.",
        "Je veux qu'ils ressentent la solitude d'une armure vide qui cherche pourquoi elle existe. La tendresse d'une enfant qui redonne vie à un monde mourant. Ce mélange étrange d'émerveillement et de peur quand la forêt bleue s'ouvre sur une caverne géante et que quelque chose d'ancien bouge dans la brume.",
        "Si l'IA me permet de rendre cette émotion visible, elle devient plus qu'un outil. Elle devient un pont entre l'imagination et la production.",
        "C'est ce qui m'enthousiasme le plus.",
        "Pas l'idée que l'IA remplacera les artistes.",
        "L'idée qu'elle peut aider plus de gens à devenir des conteurs.",
      ],
    },
    {
      heading: "Un message aux créateurs",
      paragraphs: [
        "Si vous avez une histoire dans la tête, commencez.",
        "Commencez par un personnage.",
        "Par une image.",
        "Par une scène.",
        "Par une bible de monde.",
        "Par un seul moment émotionnel auquel vous ne pouvez pas arrêter de penser.",
        "Vous n'avez pas besoin de tout savoir au départ. Lost Garden a beaucoup changé pendant que je le construisais. Le monde s'est clarifié scène après scène. Les personnages sont devenus plus forts parce que je les testais, les voyais, les affinais.",
        "L'IA rend l'itération possible à une vitesse inédite.",
        "Et peut-être que c'est la vraie révolution.",
        "Pas que les machines créent des histoires à notre place.",
        "Mais que des gens jamais admis dans l'ancien système de production puissent enfin essayer de donner vie à leurs mondes.",
        "Lost Garden est ma tentative.",
        "Un chevalier creux.",
        "Une enfant nommée Rose.",
        "Une forêt bleue sous le monde.",
        "Et quelque part dans l'obscurité, un œil ancien qui s'ouvre.",
        "J'espère que cela inspirera d'autres à créer le leur.",
      ],
    },
  ],
};
