/** Bosses: the Machine, the Décrocheur, the Dark Knight. */
import type { Palette } from "../pixel";

function rows(width: number, ...list: string[]): string[] {
  for (const r of list) {
    if (r.length !== width) throw new Error(`row width ${r.length} != ${width}: ${r}`);
  }
  return list;
}

/* La Machine: red and black spider body, two orange eyes, a drill, tentacle legs. 72x52. */
export const MACHINE_PALETTE: Palette = {
  k: "#20202b",
  K: "#343446",
  u: "#12121a",
  r: "#7d2323",
  R: "#b23535",
  x: "#d94a4a",
  o: "#ff9a2a",
  O: "#ffd27a",
  g: "#707684",
  G: "#a4aab6",
  t: "#4a4a58",
};
export const MACHINE = rows(
  72,
  "..........................kkkkkkkkkkkkkkkkkkkk..........................",
  ".......................kkkKKKKKKKKKKKKKKKKKKKKkkk.......................",
  "....................kkkKKKKKKKKrrrrrrrrrrKKKKKKKKkkk....................",
  "..................kkKKKKKKrrrrrRRRRRRRRRRrrrrrKKKKKKkk..................",
  "................kkKKKKrrrrRRRRRRRRRxRRRRRRRRRrrrrKKKKkk.................",
  "...............kKKKrrrRRRRRRRRxxRRRRRRRRRRxRRRRRRrrrKKKk................",
  "..............kKKrrRRRRRRRRxRRRRRRRRRRRRRRRRRRRRRRRRrrKKk...............",
  ".............kKKrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrKKk..............",
  "............kKKrRRRRRRRRggggggRRRRRRRRRRRRggggggRRRRRRRrKKk.............",
  "............kKrRRRRRRRgggGGGGgggRRRRRRRRgggGGGGgggRRRRRRrKk.............",
  "...........kKrRRRRRRRggGooooooGggRRRRRRggGooooooGggRRRRRRrKk............",
  "...........kKrRRRRRRggGoOOooooooGgRRRRRRgGoOOooooooGggRRRRRrKk..........",
  "..........kKrRRRRRRRgGoOOOooooooogRRRRRRgoOOOooooooooGgRRRRRRrKk........",
  "..........kKrRRRRRRRgGoooooooooooogRRRRgooooooooooooGgRRRRRRrKk.........",
  "..........kKrRRRRRRRgGoooooooooooogRRRRgooooooooooooGgRRRRRRrKk.........",
  "..........kKrRRRRRRRRgGooooooooooGgRRRRgGooooooooooGgRRRRRRRrKk.........",
  "...........kKrRRRRRRRggGooooooooGggRRRRggGooooooooGggRRRRRRrKk..........",
  "...........kKrRRRRRRRRggGGooooGGggRRRRRRggGGooooGGggRRRRRRRrKk..........",
  "............kKrRRRRRRRRRgggggggggRRRRRRRRgggggggggRRRRRRRRrKk...........",
  "............kKKrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrKKk..........",
  ".............kKKrrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrrKKk...........",
  "..............kKKKrrrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrrrKKKk............",
  "...............kkKKKKrrrrrRRRRRRRRRRRRRRRRRRRRRRrrrrrKKKKkk.............",
  ".................kkKKKKKKrrrrrrrrrrrrrrrrrrrrrrrrKKKKKKkk...............",
  "...................kkkKKKKKKKKKKKKKGGGGGGKKKKKKKKKKKkkk.................",
  "......................kkkkkkkkkkkkkGgggggGkkkkkkkkkkk...................",
  "...............kkkk........kk......GgggggG......kk........kkkk..........",
  ".............kkk..kkk.....kkk......GgggggG......kkk.....kkk..kkk........",
  "...........kkk......kkk..kkk.......GgggggG.......kkk..kkk......kkk......",
  ".........kkk..........kkkkk........GgggggG........kkkkk..........kkk....",
  ".......kkk............kkk..........GgggggG..........kkk............kkk..",
  ".....kkk.............kkk...........GgggggG...........kkk.............kkk",
  "....kk..............kkk............GgggggG............kkk..............k",
  "...kk..............kkk.............GgggggG.............kkk..............",
  "..kk..............kkk..............GgggggG..............kkk.............",
  ".kk..............kkk...............GgggggG...............kkk............",
  ".k..............kkk.................GgggG.................kkk...........",
  "k..............kkk..................GgggG..................kkk..........",
  "k.............kkk...................GgggG...................kkk.........",
  "..............kk....................GgggG....................kk.........",
  ".............kk.....................tGgGt.....................kk........",
  ".............k......................tgggt......................k........",
  "....................................tgggt...............................",
  "....................................ttgtt...............................",
  ".....................................ttt................................",
  "......................................t.................................",
  "........................................................................",
  "........................................................................",
  "........................................................................",
  "........................................................................",
  "........................................................................",
  "........................................................................",
);

/* Le Décrocheur: tall, black patterned coat, white diamond mask, antlers of dead branches. 40x72. */
export const DECROCHEUR_PALETTE: Palette = {
  k: "#0f0f16",
  K: "#1e1e2a",
  u: "#07070c",
  w: "#e8e4d8",
  W: "#f8f6ef",
  d: "#111111",
  m: "#2a2a38", // diamond pattern
  n: "#3a3a4a",
};
export const DECROCHEUR = rows(
  40,
  "...w.......w.........w.......w..........",
  "...w...w...w.w.....w.w...w...w..........",
  "....w..w..w..w.....w..w..w..w...........",
  "....w.w..w...w.....w...w..w.w...........",
  ".....ww.w....w.w.w.w....w.ww............",
  "......ww.....www.www.....ww.............",
  ".......ww...ww.....ww...ww..............",
  "........ww..w.......w..ww...............",
  ".........wwwwWWWWWWWwwww................",
  "..........wWWWWWWWWWWWw.................",
  "..........wWWWWWWWWWWWw.................",
  "...........wWWWWdWWWWw..................",
  "...........wWWWdWdWWWw..................",
  "...........wWWdWWWdWWw..................",
  "............wWWdWdWWw...................",
  "............wWWWdWWWw...................",
  ".............wWWWWWw....................",
  "..............wWWWw.....................",
  "...............wWw......................",
  "................k.......................",
  "..............kkkkk.....................",
  ".............kkKKKkk....................",
  "...........kkkKKKKKkkk..................",
  "..........kkKKKKKKKKKkk.................",
  ".........kkKKKKmKKKKKKkk................",
  ".........kKKKKmnmKKKKKKk................",
  "........kkKKKKKmKKKKKKKkk...............",
  "........kKKKKKKKKKKKKKKKk...............",
  "........kKKKKKKKKKmKKKKKk...............",
  "........kKKmKKKKKmnmKKKKk...............",
  ".......kkKmnmKKKKKmKKKKKkk..............",
  ".......kKKKmKKKKKKKKKKKKKk..............",
  ".......kKKKKKKKKKKKKKKKKKk..............",
  ".......kKKKKKKKmKKKKKKKKKk..............",
  ".......kKKKKKKmnmKKKKmKKKk..............",
  "......kkKKKKKKKmKKKKmnmKKkk.............",
  "......kKKKmKKKKKKKKKKmKKKKk.............",
  "......kKKmnmKKKKKKKKKKKKKKk.............",
  "......kKKKmKKKKKKKKKKKKKKKk.............",
  "......kKKKKKKKKKKmKKKKKKKKk.............",
  ".....kkKKKKKKKKKmnmKKKKKKKkk............",
  ".....kKKKKKKKKKKKmKKKKmKKKKk............",
  ".....kKKKKmKKKKKKKKKKmnmKKKk............",
  ".....kKKKmnmKKKKKKKKKKmKKKKk............",
  ".....kKKKKmKKKKKKKKKKKKKKKKk............",
  "....kkKKKKKKKKKKKKKKKKKKKKKkk...........",
  "....kKKKKKKKKKKmKKKKKKKKKKKKk...........",
  "....kKKKKKKKKKmnmKKKKKmKKKKKk...........",
  "....kKKKmKKKKKKmKKKKKmnmKKKKk...........",
  "....kKKmnmKKKKKKKKKKKKmKKKKKk...........",
  "....kKKKmKKKKKKKKKKKKKKKKKKKk...........",
  "...kkKKKKKKKKKKKKKKKKKKKKKKKkk..........",
  "...kKKKKKKKKKKKKKKKKKKKKKKKKKk..........",
  "...kKKKKKKKKKKKKmKKKKKKKKKKKKk..........",
  "...kKKKKKmKKKKKmnmKKKKKKmKKKKk..........",
  "...kKKKKmnmKKKKKmKKKKKKmnmKKKk..........",
  "...kKKKKKmKKKKKKKKKKKKKKmKKKKk..........",
  "..kkKKKKKKKKKKKKKKKKKKKKKKKKKkk.........",
  "..kKKKKKKKKKKKKKKKKKKKKKKKKKKKk.........",
  "..kKKKKKKKKKKKKKKKKKKKKKKKKKKKk.........",
  "..k.kKKKk.kKKKk.kKKKk.kKKKk.k.k.........",
  "..k.kKKk..kKKk..kKKk..kKKk..k.k.........",
  "....kKk...kKk...kKk...kKk...............",
  "....kk....kk....kk....kk................",
  "....k.....k.....k.....k.................",
  "....u.....u...........u.................",
  "....u.....u...........u.................",
  "...uu....uu..........uu.................",
  "...uu....uu..........uu.................",
  "........................................",
  "........................................",
  "........................................",
);

/* The Décrocheur's scythe. 36x36. */
export const SCYTHE_PALETTE: Palette = { g: "#5a5a66", G: "#78788a", s: "#cfcabd", S: "#ffffff", u: "#9b968a" };
export const SCYTHE = rows(
  36,
  "................ssssssssss..........",
  ".............sssSSSSSSSSSsss........",
  "...........sssSSSS.......SSss.......",
  ".........sssSSS............Sss......",
  "........ssSSS...............ss......",
  ".......ssSS..................s......",
  "......ssSS..........................",
  ".....ssS............................",
  "....ssS.............................",
  "....sS..............................",
  "...ss...............................",
  "...su...............................",
  "...u.................Gg.............",
  "....................Gg..............",
  "...................Gg...............",
  "..................Gg................",
  ".................Gg.................",
  "................Gg..................",
  "...............Gg...................",
  "..............Gg....................",
  ".............Gg.....................",
  "............Gg......................",
  "...........Gg.......................",
  "..........Gg........................",
  ".........Gg.........................",
  "........Gg..........................",
  ".......Gg...........................",
  "......Gg............................",
  ".....Gg.............................",
  "....Gg..............................",
  "...Gg...............................",
  "..Gg................................",
  ".Gg.................................",
  "Gg..................................",
  "....................................",
  "....................................",
);

/* Le Chevalier Sombre: dark green armour, torn white hood and cape. 28x44, 2 frames. */
export const SOMBRE_PALETTE: Palette = {
  g: "#2f4a3a",
  G: "#446a52",
  u: "#1f3327",
  w: "#efece4",
  W: "#fbfaf6",
  v: "#cfcbc1",
  k: "#0f1013",
  t: "#5a3d2a",
  s: "#9aa3b1",
};
export const SOMBRE_A = rows(
  28,
  ".........wwwwwwww...........",
  "........wWWWWWWWWw..........",
  ".......wWWggggggWWw.........",
  ".......wWgGGGGGGgWw.........",
  ".......wWgGGGGGGgWw.........",
  ".......wWgkkkkkkgWw.........",
  ".......wWggGGGGggWw.........",
  ".......wWggggggggWw.........",
  "......wWWwggggggwWWw........",
  ".....wWWWWwwwwwwWWWWw.......",
  "....wWWWGGGGGGGGGGWWWw......",
  "....wWWgGGGGGGGGGGgWWw......",
  "....wWWgGGgGGGGgGGgWWw......",
  "....wWW.gGGGGGGGGg.WWw......",
  "....wWW.gGGGGGGGGg.WWw......",
  "....wWW.tttttttttt.WWw......",
  "....wWW.gGGGGGGGGg.WWw......",
  "....wWWgGGGGGGGGGGgWWw......",
  "....wWWgGGGGGGGGGGgWWw......",
  "....wWWgGGGGGGGGGGgWWw......",
  "....vWWuGGGGGGGGGGuWWv......",
  "....vWW.uGGGGGGGGu.WWv......",
  "....vW..uGGGGGGGGu..Wv......",
  "....vW...GGGG.GGGG..Wv......",
  "....v....GGGG.GGGG...v......",
  ".........gGGg.gGGg..........",
  ".........gGGg.gGGg..........",
  ".........GGGG.GGGG..........",
  ".........gGGg.gGGg..........",
  ".........gGGg.gGGg..........",
  ".........uGGu.uGGu..........",
  ".........gGGg.gGGg..........",
  ".........gGGg.gGGg..........",
  ".........uuuu.uuuu..........",
  "........kkkkk.kkkkk.........",
  ".......kkkkkk.kkkkkk........",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
);
export const SOMBRE_B = [
  ...SOMBRE_A.slice(0, 23),
  "....vW..GGGG...GGGG.Wv......",
  "....v..GGGG.....GGGG.v......",
  ".......gGGg.....gGGg........",
  "......gGGg.......gGGg.......",
  "......GGGG.......GGGG.......",
  ".....gGGg.........gGGg......",
  ".....gGGg.........gGGg......",
  ".....uGGu.........uGGu......",
  "....gGGg...........gGGg.....",
  "....gGGg...........gGGg.....",
  "....uuuu...........uuuu.....",
  "...kkkkk...........kkkkk....",
  "..kkkkkk...........kkkkkk...",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
  "............................",
];

export const GREATSWORD_PALETTE: Palette = { s: "#9aa3b1", S: "#d5dbe4", t: "#5a3d2a", h: "#3a2a1e", g: "#c9a24a" };
export const GREATSWORD = rows(
  6,
  "..Ss..",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  ".sSss.",
  "gggggg",
  "..hh..",
  "..hh..",
  "..hh..",
  "..hh..",
  "..tt..",
  ".tttt.",
  "......",
);
