/** Enemies of the Dessous. */
import type { Palette } from "../pixel";

function rows(width: number, ...list: string[]): string[] {
  for (const r of list) {
    if (r.length !== width) throw new Error(`row width ${r.length} != ${width}: ${r}`);
  }
  return list;
}

/* Spore: a glowing blue mushroom that hops. 18x18. */
export const SPORE_PALETTE: Palette = {
  c: "#3fa9e8",
  C: "#8fe3ff",
  u: "#2a7cb8",
  s: "#d3dde4",
  S: "#f1f5f8",
  t: "#9fb0bd",
  e: "#101018",
  g: "#c9f3ff",
};
export const SPORE_A = rows(
  18,
  "......CCCCCC......",
  "....CCccccccCC....",
  "...CccCCccCCccC...",
  "..CcccccccccccCC..",
  ".CccccCCcccccccCu.",
  ".Cccccccccccccccu.",
  "CcccccccccCCcccccu",
  "cccuuuuuuuuuuuuccu",
  ".uu.uuu.uuu.uu.uu.",
  ".....SssssssS.....",
  ".....SseSSesS.....",
  ".....SsssssssS....",
  ".....ssssssssst...",
  ".....tsssssstt....",
  "......tsssstt.....",
  ".....tt.ss.tt.....",
  "....tt..tt..tt....",
  "...ttt......ttt...",
);
export const SPORE_B = rows(
  18,
  "..................",
  "..................",
  "......CCCCCC......",
  "....CCccccccCC....",
  "..CCccCCccCCccCC..",
  ".CcccccccccccccCu.",
  "CccccccCCcccccccuu",
  "cccccccccccccccccu",
  "cccuuuuuuuuuuuuccu",
  ".uu.uuu.uuu.uu.uu.",
  ".....SssssssS.....",
  ".....SseSSesS.....",
  "....SssssssssS....",
  "...tssssssssssst..",
  "..ttsst....tsstt..",
  ".ttt..........ttt.",
  "tt..............tt",
  "..................",
);

/* Méduse: translucent jellyfish. 18x22. */
export const MEDUSE_PALETTE: Palette = {
  m: "#7fd8ff",
  M: "#d4f4ff",
  d: "#3f8fc4",
  i: "#b3ecff",
  t: "#9fe4ff",
  T: "#c8f0ff",
};
export const MEDUSE_A = rows(
  18,
  "......MMMMMM......",
  "....MMmmmmmmMM....",
  "...MmmmiimmmmmM...",
  "..MmmmiiimmmmmmM..",
  ".MmmmmiimmmmmmmmM.",
  ".MmmmmmmmmmmmmmmM.",
  "MmmmmmmmmmmmmmmmmM",
  "MmmmddmmmddmmmddmM",
  ".mmmmmmmmmmmmmmmm.",
  "..mmdmmdmmdmmdmm..",
  "..T.t..t..t..t.T..",
  "..t.t..T..t..T.t..",
  ".t..T..t..T..t..t.",
  ".t..t..t..t..t..t.",
  ".T..t..T..t..T..T.",
  "..t..t..t..t..t...",
  "..t..T..t..T..t...",
  "...t..t..t..t.....",
  "...t..t..t..t.....",
  "....t..t..t.......",
  "....T..T..T.......",
  "..................",
);
export const MEDUSE_B = rows(
  18,
  "..................",
  "......MMMMMM......",
  "....MMmmmmmmMM....",
  "...MmmmiimmmmmM...",
  "..MmmmiiimmmmmmM..",
  ".MmmmmiimmmmmmmmM.",
  "MmmmmmmmmmmmmmmmmM",
  "MmmmddmmmddmmmddmM",
  ".mmmmmmmmmmmmmmmm.",
  "..mmdmmdmmdmmdmm..",
  "..t..T..t..T..t...",
  "..T..t..T..t..T...",
  "...t..t..t..t..t..",
  "...t..T..t..T..t..",
  "....t..t..t..t..t.",
  "....T..t..T..t..t.",
  ".....t..t..t..t...",
  ".....t..T..t..T...",
  "......t..t..t.....",
  "......T..t..T.....",
  ".......t..t.......",
  "..................",
);

/* Pénitent: hooded, white long mask, 18x36. */
export const PENITENT_PALETTE: Palette = {
  r: "#1c1e2a",
  R: "#2c2f3e",
  n: "#121319",
  w: "#ebe8e0",
  W: "#fbfaf6",
  u: "#c9c4b8",
  e: "#0b0b10",
};
export const PENITENT_A = rows(
  18,
  ".......RRRR.......",
  "......RrrrrR......",
  ".....RrrrrrrR.....",
  ".....rrWwwwrr.....",
  "....rrrWwwwurr....",
  "....rrrWewwurr....",
  "....rrrWwwwurr....",
  "....rrrWwwwurr....",
  "....rrrWwweurr....",
  "....rrrrWwwurr....",
  "....rrrrWwwurr....",
  "....RrrrWwwurrr...",
  "...RrrrrWwwurrrR..",
  "...rrrrrWwwurrrr..",
  "...rrrrrrWwurrrr..",
  "...rrrrrrWwurrrr..",
  "..RrrrrrrWwurrrrR.",
  "..rrrrrrrWwurrrrr.",
  "..rrrrrrrrwurrrrr.",
  "..rrrrrrrrrrrrrrr.",
  "..rrrRrrrrrrrRrrr.",
  "..rrrRrrrrrrrRrrr.",
  ".RrrrRrrrrrrrRrrrR",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".rrrrrrrrrrrrrrrrr",
  ".nrrrrrrrrrrrrrrrn",
  ".nnrrrrrrrrrrrrrnn",
  ".nnnnnnnnnnnnnnnnn",
  "..................",
);
export const PENITENT_B = [...PENITENT_A.slice(0, 31), ".rrrrrrrrrrrrrrrrr", ".nrrrrrrrrrrrrrrnn", ".nnrrrrrrrrrrrrnnn", "..nnnnnnnnnnnnnn..", ".................."];

/* Rouage: crawling red and black machine, orange eye. 24x18. */
export const ROUAGE_PALETTE: Palette = {
  k: "#1e1e28",
  K: "#31313f",
  r: "#8f2a2a",
  R: "#c43b3b",
  u: "#5e1c1c",
  o: "#ff9a2a",
  O: "#ffd27a",
  g: "#7d818c",
  G: "#a4a8b3",
};
export const ROUAGE_A = rows(
  24,
  "........kkkkkkkk........",
  "......kkRRRRRRRRkk......",
  ".....kRRrrrrrrrrRRk.....",
  "....kRrrrrrrrrrrrrRk....",
  "...kRrrrrgggggrrrrrRk...",
  "...kRrrrgOoooogrrrrRk...",
  "..kRrrrrgooOoogrrrrrRk..",
  "..kurrrrgooooogrrrrruk..",
  "..kuurrrrgggggrrrrruuk..",
  "...kuuuuuuuuuuuuuuuuk...",
  "...kGkGkkGkkkkGkkGkGk...",
  "..kk.k.kk.k..k.kk.k.kk..",
  ".kk..k.k..k..k..k.k..kk.",
  "kk..kk.k..k..k..k.kk..kk",
  "k..kk..k.kk..kk.k..kk..k",
  "k.kk...k.k....k.k...kk.k",
  "kkk...kk.k....k.kk...kkk",
  "......k..........k......",
);
export const ROUAGE_B = [
  ...ROUAGE_A.slice(0, 11),
  "...k.kk.k.kk.kk.k.kk.k..",
  "..kk.k..k.k..k.k..k..kk.",
  "..k..k.kk.k..k.kk.k..k..",
  ".kk.kk.k..k..k..k.kk.kk.",
  ".k..k..k.kk..kk.k..k..k.",
  ".kkkk..k.k....k.k..kkkk.",
  "..........................".slice(0, 24),
];

/* Masse-loup: a pack fused into one running mass. 30x18. */
export const LOUP_PALETTE: Palette = {
  k: "#1d2030",
  K: "#2f3348",
  u: "#12141f",
  e: "#9fd6ff",
  E: "#dff4ff",
  w: "#d3d6e0",
  f: "#3d4260",
};
export const LOUP_A = rows(
  30,
  "......................kk......",
  "..........kkkkkkkkkkkkKKk.....",
  "........kkKKKKKKKKKKKKKKKkk...",
  "......kkKKKKKKKfKKKKKKeEKKkk..",
  ".....kKKKKfKKKKKKKKKKKKKKKKkk.",
  "....kKKKKKKKKKKKKKKfKKKKKKKKkk",
  "...kKKKKKKKfKKKKKKKKKKKKKKwwww",
  "..kKKKKKKKKKKKKKKKKKKKKKKkkw.w",
  "..kKKKfKKKKKKKKKKKKKKKKKKKk...",
  "..kKKKKKKKKKKKKKKfKKKKKKKk....",
  "...kKKKKKKKKKKKKKKKKKKKKk.....",
  "...kuKKkkKKKKKkkKKKKkkKKk.....",
  "....kuKk..kKKk..kKKk..kKk.....",
  "....kKk...kKk...kKk...kK......",
  "...kKk...kKk...kKk...kKk......",
  "..kKk...kKk...kKk...kKk.......",
  ".kkk...kkk...kkk...kkk........",
  "..............................",
);
export const LOUP_B = [
  ...LOUP_A.slice(0, 11),
  "...kuKKkkKKKKKkkKKKKkkKKk.....",
  ".....kKk.kKk..kKk..kKk.kK.....",
  ".....kKk..kKk..kKk..kKk.......",
  "....kKk...kKk...kKk..kKk......",
  "....kKk....kKk...kKk..kKk.....",
  "...kkk....kkk...kkk....kkk....",
  "..............................",
];

/* Reptilien pâle: a tall thin white lizard with amber eyes. 20x36. */
export const REPTILE_PALETTE: Palette = {
  w: "#dfe4ec",
  W: "#f6f8fb",
  u: "#b3bcc9",
  y: "#f2c14e",
  Y: "#ffe08a",
  b: "#2f4a6b",
  B: "#3f6088",
  e: "#111111",
  t: "#8e9aa8",
};
export const REPTILE_A = rows(
  20,
  ".....W.W.W..........",
  "....WWWWWWW.........",
  "...WWyYWWyYW........",
  "...WWyeWWyeW........",
  "...WWWWWWWWWW.......",
  "....uWWWwWWWu.......",
  ".....uWwwwWu........",
  "......wwww..........",
  ".....wwwwww.........",
  "....wwwwwwww........",
  "...wwwuwwwwuww......",
  "..ww..wwwwww.ww.....",
  "..w...wwwwww..w.....",
  "..w...wwwwww..w.....",
  "..u...uwwwwu..u.....",
  "......uwwwwu........",
  ".....bBbbbbBb.......",
  ".....bbbbbbbb.......",
  ".....bbbbbbbbb.t....",
  ".....wwwbbbwww.tt...",
  ".....www...www..tt..",
  ".....www...www...tt.",
  ".....www...www....tt",
  ".....www...www......",
  ".....www...www......",
  ".....www...www......",
  ".....www...www......",
  ".....www...www......",
  ".....uww...uww......",
  ".....uww...uww......",
  ".....www...www......",
  "....wwww...wwww.....",
  "...wwwww...wwwww....",
  "..uuuuuu...uuuuuu...",
  "....................",
  "....................",
);
export const REPTILE_B = [
  ...REPTILE_A.slice(0, 19),
  "....wwwwbbbwwww.tt..",
  "...www.....www..tt..",
  "..www.......www..tt.",
  ".www.........www..tt",
  ".www.........www....",
  "www...........www...",
  "www...........www...",
  "www...........www...",
  "uww...........uww...",
  "uww...........uww...",
  "www...........www...",
  "www...........wwww..",
  "wwww.........wwwww..",
  "uuuu.........uuuuu..",
  "....................",
  "....................",
];

/* Colosse cuirassé: a mound of shields with skulls, bone legs, pale mane. 48x36. */
export const COLOSSE_PALETTE: Palette = {
  s: "#6b6355",
  S: "#8a7f6b",
  d: "#4a443b",
  D: "#332f29",
  b: "#e5dccb",
  B: "#f5efe0",
  p: "#4a2f4f",
  P: "#63406a",
  h: "#efe7d1",
  H: "#fbf6ea",
  k: "#2a2622",
  e: "#111111",
  r: "#8a6b3f",
};
export const COLOSSE_A = rows(
  48,
  "...................ddddddddd....................",
  ".................ddSSSSSSSSSdd..................",
  "..............dddSSSeSSSSSeSSSddd...............",
  "...........dddSSSSSSSSSSSSSSSSSSSdd.............",
  ".........ddSSSSSSSSdSSSSSSSSdSSSSSSdd...........",
  "........dSSSSSSSSSSdddddddddSSSSSSSSSd..........",
  ".......dSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSd.........",
  "......dSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSd........",
  ".....dSSSSSSdSSSSSSSSdSSSSSSSSdSSSSSSSSSd.......",
  "....dSSSSSSSdSSSSSSSSdSSSSSSSSdSSSSSSSSSSd......",
  "...dSSSSSSSSdSSSSSSSSdSSSSSSSSdSSSSSSSSSSSd.....",
  "...dSSSSSSSSdSSSSSSSSdSSSSSSSSdSSSSSSSSSSSd.....",
  "..dSSsSSSSSSdSSsSSSSSdSSSSsSSSdSSSSSSSsSSSSd....",
  "..dSSSSSSSSSdSSSSSSSSdSSSSSSSSdSSSSSSSSSSSSd....",
  "..dssssssssdssssssssssdssssssssdsssssssssssd....",
  "..dHhhhhhsdssssssssssssdsssssssssdsssssssssrrrr.",
  "..dHhhhhhhhdddddddddddddddddddddddddddddddrrrrr.",
  "..dHhhhhhhhhPppppppppppppppppppppppppppppp.rrr..",
  "...HhhhhhhhhPppppppppppppppppppppppppppppp......",
  "...Hhhhhhhhh.PpppppppppppppppppppppppppppP......",
  "...Hhh.hhhhh.ppppppppppppppppppppppppppppP......",
  "...Hhh.hhhh..pppppppppppppppppppppppppppP.......",
  "...Hh..hhh....ppp..pppp....ppp....ppp...........",
  "...Hh..hh.....BbB..BbbB....BbB....BbB...........",
  "...H...h......bbb..bbbb....bbb....bbb...........",
  "..............bbb..bbb.....bbb....bbb...........",
  "..............bbb..bbb.....bbb....bbb...........",
  "..............bbb..bbb.....bbb....bbb...........",
  ".............bbb..bbb.....bbb....bbb............",
  ".............bbb..bbb.....bbb....bbb............",
  ".............bbb..bbb.....bbb....bbb............",
  "............kkkk.kkkk....kkkk...kkkk............",
  "...........kkkk.kkkk....kkkk...kkkk.............",
  "................................................",
  "................................................",
  "................................................",
);
export const COLOSSE_B = [
  ...COLOSSE_A.slice(0, 24),
  "...H...h......bbb..bbbb....bbb....bbb...........",
  "..............bbb...bbb....bbb.....bbb..........",
  "...............bbb..bbb.....bbb....bbb..........",
  "...............bbb...bbb....bbb.....bbb.........",
  "................bbb..bbb.....bbb....bbb.........",
  "................bbb...bbb....bbb.....bbb........",
  "................bbb...bbb....bbb.....bbb........",
  "...............kkkk..kkkk...kkkk....kkkk........",
  "..............kkkk..kkkk...kkkk....kkkk.........",
  "................................................",
  "................................................",
  "................................................",
];

/* Golem: an empty red-lit armour from the castle hall. 20x36. */
export const GOLEM_PALETTE: Palette = {
  a: "#6e3b3b",
  A: "#914f4f",
  u: "#4a2626",
  d: "#2f1818",
  e: "#ff9a2a",
  E: "#ffd27a",
  g: "#9c7b3a",
};
export const GOLEM_A = rows(
  20,
  "......AAAAAAAA......",
  ".....AaaaaaaaaA.....",
  ".....AaaaaaaaaA.....",
  ".....AaaEeaaEeA.....",
  ".....AaaaaaaaaA.....",
  ".....uaaaaaaaau.....",
  "......uuuuuuuu......",
  "....AAAAaaaaAAAA....",
  "...AaaaAaaaaAaaaA...",
  "..AaaaaAaaaaAaaaaA..",
  "..AaaaaAggggAaaaaA..",
  "..uaauuAaaaaAuuaau..",
  "..uaa..AaaaaA..aau..",
  "..uaa..AaaaaA..aau..",
  "..uaa..AaaaaA..aau..",
  "..dud..uaaaau..dud..",
  "..dud..AaaaaA..dud..",
  ".......uAAAAu.......",
  "......AaaaaaaaA.....",
  "......AaaaaaaaA.....",
  "......uaaaaaaau.....",
  ".......aaa..aaa.....",
  ".......aaa..aaa.....",
  ".......AAA..AAA.....",
  ".......aaa..aaa.....",
  ".......aaa..aaa.....",
  ".......uaa..uaa.....",
  ".......aaa..aaa.....",
  ".......aaa..aaa.....",
  ".......ddd..ddd.....",
  "......dddd..dddd....",
  ".....ddddd..ddddd...",
  "....................",
  "....................",
  "....................",
  "....................",
);
export const GOLEM_B = [
  ...GOLEM_A.slice(0, 21),
  "......aaa....aaa....",
  "......aaa....aaa....",
  ".....AAA......AAA...",
  ".....aaa......aaa...",
  "....aaa........aaa..",
  "....uaa........uaa..",
  "...aaa..........aaa.",
  "...aaa..........aaa.",
  "...ddd..........ddd.",
  "..dddd..........dddd",
  ".ddddd..........dddd",
  "....................",
  "....................",
  "....................",
  "....................",
];

/* Souris habillée: Bourdon's mouse with a bell. 12x12. */
export const SOURIS_PALETTE: Palette = {
  m: "#a89f94",
  M: "#d1c9bf",
  p: "#e7b8c0",
  e: "#111111",
  g: "#e0b04a",
  r: "#c46a5a",
  R: "#de8a78",
};
export const SOURIS = rows(
  12,
  ".mm......mm.",
  "mpmm....mmpm",
  ".mmmmmmmmmm.",
  "..mmemmemm..",
  "..mmmmmmmm..",
  "...mmMMmm...",
  "..RrrrrrrR..",
  "..rrrgrrrr..",
  "..rrrrrrrr..",
  "...mmmmmm...",
  "..mm....mm..",
  "..m......m..",
);
