/** Chests, items, projectiles, tiles and decorations. */
import type { Palette } from "../pixel";

function rows(width: number, ...list: string[]): string[] {
  for (const r of list) {
    if (r.length !== width) throw new Error(`row width ${r.length} != ${width}: ${r}`);
  }
  return list;
}

/* Chest 24x20. */
export const CHEST_PALETTE: Palette = {
  w: "#6b4a2a",
  W: "#8f6538",
  u: "#4a3119",
  g: "#d9b24a",
  G: "#f1d27a",
  k: "#2a1d10",
  i: "#3a3230",
};
export const CHEST_CLOSED = rows(
  24,
  ".....kkkkkkkkkkkkkkk....",
  "...kkWWWWWWWWWWWWWWWkk..",
  "..kWWwwwwwwwwwwwwwwwWWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kggggggggggggggggggGk.",
  "..kWwwwwwwwwgGwwwwwwwWk.",
  "..kWwwwwwwwgGGgwwwwwwWk.",
  "..kWwwwwwwwwggwwwwwwwWk.",
  "..kWwwwwwwwwiiwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kggggggggggggggggggGk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kuwwwwwwwwwwwwwwwwwuk.",
  "..kkkkkkkkkkkkkkkkkkkkk.",
  "........................",
  "........................",
  "........................",
  "........................",
);
export const CHEST_OPEN = rows(
  24,
  "..kkkkkkkkkkkkkkkkkkkkk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kkkkkkkkkkkkkkkkkkkkk.",
  "...k.................k..",
  "..kggggggggggggggggggGk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kggggggggggggggggggGk.",
  "..kWwwwwwwwwwwwwwwwwwWk.",
  "..kuwwwwwwwwwwwwwwwwwuk.",
  "..kkkkkkkkkkkkkkkkkkkkk.",
  "........................",
  "........................",
  "........................",
  "........................",
);

/* Items 14x14. */
export const ITEM_PALETTE: Palette = {
  y: "#fff1a8",
  Y: "#ffffff",
  o: "#ffb347",
  g: "#d9b24a",
  G: "#f1d27a",
  s: "#c9d0da",
  S: "#eef1f5",
  t: "#5a3d2a",
  b: "#4f6b5a",
  B: "#7a9a84",
  m: "#7fd8ff",
  M: "#c9f1ff",
  c: "#9c8862",
  C: "#d9c59f",
  v: "#bfa981",
  w: "#f4f4f0",
  W: "#ffffff",
  L: "#4a8a6a",
  l: "#6fb08a",
};
export const ITEM_LUEUR = rows(
  14,
  "......yy......",
  ".....yYYy.....",
  "....yYYYYy....",
  "...yYYYYYYy...",
  "..yYYYYYYYYy..",
  "..yYYYYYYYYy..",
  "..yYYYYYYYYy..",
  "...yYYYYYYy...",
  "....yYYYYy....",
  ".....yYYy.....",
  "......oo......",
  "......oo......",
  ".....oooo.....",
  "..............",
);
export const ITEM_CLE = rows(
  14,
  "....GGGGG.....",
  "...Gg...gG....",
  "...Gg...gG....",
  "...Gg...gG....",
  "....GgggG.....",
  ".....Gg.......",
  ".....Gg.......",
  ".....Gg.......",
  ".....GgGG.....",
  ".....Gg.......",
  ".....GgGG.....",
  ".....Gg.......",
  ".....gg.......",
  "..............",
);
export const ITEM_DAGUE = rows(
  14,
  "............SS",
  "...........Ss.",
  "..........Ss..",
  ".........Ss...",
  "........Ss....",
  ".......Ss.....",
  "......Ss......",
  ".....Ss.......",
  "...gGGg.......",
  "..tt.g........",
  ".tt...........",
  "tt............",
  "..............",
  "..............",
);
export const ITEM_CLOCHE = rows(
  14,
  "......GG......",
  ".....Bbbb.....",
  "....BbbbbB....",
  "....Bbbbbb....",
  "....Bbbbbb....",
  "....Bbbbbb....",
  "...BbbbbbbB...",
  "...Bbbbbbbb...",
  "..BbbbbbbbbB..",
  "..bbbbbbbbbb..",
  "..BBBBBBBBBB..",
  ".....GGg......",
  "......gg......",
  "..............",
);
export const ITEM_CAPE = rows(
  14,
  "...cCCCCCCc...",
  "..cCvvvvvvCc..",
  "..cCvvvvvvCc..",
  "..cCvvvvvvCc..",
  "..cCvvvvvvCc..",
  "..cCvvvvvvCc..",
  "..cCvvvvvvCc..",
  "..cCvvvvvvCc..",
  "..cCvvvvvvCc..",
  "..cCvcvvcvCc..",
  "..cCc.cc.cCc..",
  "..c.c....c.c..",
  "..............",
  "..............",
);
export const ITEM_MEDAILLON = rows(
  14,
  "......ss......",
  ".....s..s.....",
  "....ssssss....",
  "...sSmmmmSs...",
  "..sSmmMMmmSs..",
  "..smmMYYMmms..",
  "..smmMYYMmms..",
  "..sSmmMMmmSs..",
  "...sSmmmmSs...",
  "....ssssss....",
  "..............",
  "..............",
  "..............",
  "..............",
);
export const ITEM_LYS = rows(
  14,
  "....W....W....",
  "...WWw..wWW...",
  "...WwwWWwwW...",
  "....WwWWwW....",
  ".....WGgW.....",
  "......lL......",
  "......lL......",
  ".....LlL......",
  "....L.lL......",
  "......lL......",
  "......lL......",
  "..............",
  "..............",
  "..............",
);

export const PROJ_PALETTE: Palette = {
  ...ITEM_PALETTE,
  r: "#ff9a2a",
  R: "#ffd27a",
  x: "#ff5a2a",
};
export const PROJ_LUEUR = rows(12, "..oyYYYYyy..", ".oyYYYYYYYo.", "oyYYYYYYYYYo", ".oyYYYYYYYo.", "..oyYYYYyy..");
export const PROJ_DAGUE = rows(14, "tt............", ".ttgSSSSSSSSSS", "tt............");
export const PROJ_CLE = rows(
  12,
  "...GGGGG....",
  "..Gg...gG...",
  "..Gg...gG...",
  "...GgggG....",
  "....Gg......",
  "....Gg......",
  "....GgGG....",
  "....Gg......",
  "....GgGG....",
  "....gg......",
  "............",
  "............",
);
export const PROJ_CLOCHE = rows(
  12,
  ".....GG.....",
  "....Bbbb....",
  "...BbbbbB...",
  "...Bbbbbb...",
  "...Bbbbbb...",
  "..BbbbbbbB..",
  "..Bbbbbbbb..",
  ".BbbbbbbbbB.",
  ".BBBBBBBBBB.",
  "....GGg.....",
  ".....gg.....",
  "............",
);
export const PROJ_SPARK = rows(6, ".rRr..", "rRRRr.", "rRRRr.", ".rrr..", "......", "......");
export const PROJ_SHARD = rows(6, "..x...", ".xRx..", "xRRRx.", ".xRx..", "..x...", "......");

/* Tiles 24x24. Tiles skip the outline pass. */
export const FOREST_PALETTE: Palette = {
  m: "#3f7f6a",
  M: "#78cfa2",
  n: "#2c5d4c",
  s: "#22364d",
  S: "#33506e",
  t: "#2a4460",
  d: "#162538",
  D: "#0f1a2a",
  r: "#1a2f45",
};
export const FOREST_GROUND = rows(
  24,
  "mMmmmMmmmmmMmmmmMmmmmmMm",
  "mmmmmmmmmmmmmmmmmmmmmmmm",
  "nmmmnmmmmnmmmnmmmmnmmmnm",
  "SsssssssdsssssssssdSssss",
  "sSsssssSdsssssSsssdsssss",
  "ssssssssdsssssssssdsssss",
  "sttsssssdsssttssssdsssss",
  "ssssssssdsssssssssdsssss",
  "dddddddddddddddddddddddd",
  "sssdssssssssssdsssssssss",
  "sSsdsssSssssssdssSsssSss",
  "sssdssssssssssdsssssssss",
  "sssdsttsssssssdsssttssss",
  "sssdssssssssssdsssssssss",
  "dddddddddddddddddddddddd",
  "ssssssssssdssssssssdssss",
  "sSssssSsssdsssSsssSdssss",
  "ssssssssssdssssssssdssss",
  "sttsssssssdsssttssssdsss",
  "ssssssssssdssssssssdssss",
  "dddddddddddddddddddddddd",
  "sssssdssssssssssdsssssss",
  "sSsssdsssSssssssdsssSsss",
  "sssssdssssssssssdsssssss",
);
export const FOREST_ROCK = [...FOREST_GROUND.slice(3), ...FOREST_GROUND.slice(3, 6)];
export const FOREST_ROCK_B = [...FOREST_GROUND.slice(9), ...FOREST_GROUND.slice(3, 12)];

export const MUSHROOM_PALETTE: Palette = { c: "#3fa9e8", C: "#8fe3ff", u: "#2a7cb8", s: "#b8c6d0", S: "#dde6ec", t: "#8fa0ad" };
export const MUSHROOM_CAP = rows(
  24,
  "........CCCCCCCC........",
  "....CCCCccccccccCCCC....",
  "..CCccccCCccccCCccccCC..",
  ".CccccccccccccccccccccC.",
  "CccccccCCccccccccCCcccuu",
  "ccccccccccccccccccccccuu",
  "cuuuuuuuuuuuuuuuuuuuuuuu",
  ".uu.uuu.uuu.uuu.uuu.uu..",
  "..........SssS..........",
  "..........SssS..........",
  "..........Ssst..........",
  "..........Ssst..........",
  "..........Ssst..........",
  "..........Ssst..........",
  "..........Ssst..........",
  "..........Ssst..........",
  "..........Ssst..........",
  "..........Ssst..........",
  ".........SSsstt.........",
  ".........Sssstt.........",
  "........SSssssts........",
  "........ssssssss........",
  "........................",
  "........................",
);
export const CHAIN_PALETTE: Palette = { r: "#8a5a34", R: "#b0733f", u: "#5a3820", g: "#7c9a4a" };
export const CHAIN_PLATFORM = rows(
  24,
  ".RRRR....RRRR....RRRR...",
  "RruurRRRRruurRRRRruurRRR",
  "Rr..rrrrrr..rrrrrr..rrrr",
  "Rr..rRuuRr..rRuuRr..rRuu",
  "RruurRuuRruurRuuRruurRuu",
  ".RRRRruurRRRRruurRRRRruu",
  "....Rr..rR...Rr..rR.....",
  "....RruurR...RruurR.....",
  ".....g........g.........",
  ".....g..................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
);
export const BONE_PALETTE: Palette = {
  b: "#cfc7b4",
  B: "#f0e9d6",
  u: "#a8a08e",
  g: "#2f3038",
  G: "#41434d",
  t: "#383a44",
  d: "#1e1f26",
};
export const BONE_GROUND = rows(
  24,
  "bBbbubbbBbbbbubbbbBbbbub",
  "bbbbbbbbbbbbbbbbbbbbbbbb",
  "ubbubbbubbbbubbubbbubbub",
  "GggggggdgggggggggdGggggg",
  "gGgggggGdggggggGggdggggg",
  "ggggggggdgggggggggdggggg",
  "gttgggggdgggttggggdggggg",
  "ggggggggdgggggggggdggggg",
  "dddddddddddddddddddddddd",
  "gggdggggggggggdggggggggg",
  "gGgdgggGggggggdggGgggGgg",
  "gggdggggggggggdggggggggg",
  "gggdgttgggggggdgggttgggg",
  "gggdggggggggggdggggggggg",
  "dddddddddddddddddddddddd",
  "ggggggggggdggggggggdgggg",
  "gGggggGgggdgggGgggGdgggg",
  "ggggggggggdggggggggdgggg",
  "gttgggggggdgggttggggdggg",
  "ggggggggggdggggggggdgggg",
  "dddddddddddddddddddddddd",
  "gggggdggggggggggdggggggg",
  "gGgggdgggGggggggdgggGggg",
  "gggggdggggggggggdggggggg",
);
export const BONE_ROCK = [...BONE_GROUND.slice(3), ...BONE_GROUND.slice(3, 6)];
export const BONE_ROCK_B = [...BONE_GROUND.slice(9), ...BONE_GROUND.slice(3, 12)];

export const CASTLE_PALETTE: Palette = {
  s: "#4a4455",
  S: "#5f586c",
  t: "#3f3a4a",
  d: "#2a2632",
  r: "#7a2f38",
  R: "#a03f4a",
  u: "#5a2029",
  g: "#c9a24a",
};
export const CASTLE_STONE = rows(
  24,
  "ssssssssdsssssssssdSssss",
  "sSsssssSdsssssSsssdsssss",
  "ssssssssdsssssssssdsssss",
  "sttsssssdsssttssssdsssss",
  "ssssssssdsssssssssdsssss",
  "dddddddddddddddddddddddd",
  "sssdssssssssssdsssssssss",
  "sSsdsssSssssssdssSsssSss",
  "sssdssssssssssdsssssssss",
  "sssdsttsssssssdsssttssss",
  "sssdssssssssssdsssssssss",
  "dddddddddddddddddddddddd",
  "ssssssssssdssssssssdssss",
  "sSssssSsssdsssSsssSdssss",
  "ssssssssssdssssssssdssss",
  "sttsssssssdsssttssssdsss",
  "ssssssssssdssssssssdssss",
  "dddddddddddddddddddddddd",
  "sssssdssssssssssdsssssss",
  "sSsssdsssSssssssdsssSsss",
  "sssssdssssssssssdsssssss",
  "sssssdsttsssssssdsssttss",
  "sssssdssssssssssdsssssss",
  "dddddddddddddddddddddddd",
);
export const CASTLE_FLOOR = rows(
  24,
  "RrrrRrrrrrRrrrrRrrrrrRrr",
  "rrrrrrrrrrrrrrrrrrrrrrrr",
  "urrurrrurrrrurrurrrurrur",
  ...CASTLE_STONE.slice(3),
);
export const BEAM_PALETTE: Palette = { w: "#5a4530", W: "#7d6244", u: "#3a2a1e", k: "#221810", g: "#8a7050" };
export const CASTLE_BEAM = rows(
  24,
  "WWWWWWWWWWWWWWWWWWWWWWWW",
  "wwwwWwwwwwwwWwwwwwwwWwww",
  "wwwwwwwwwwwwwwwwwwwwwwww",
  "uwwuwwwwuwwwwwwuwwwwwwuw",
  "kkkkkkkkkkkkkkkkkkkkkkkk",
  "...g................g...",
  "...g................g...",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
);
export const THORNS_PALETTE: Palette = { w: "#5d5a6a", W: "#e8e6ef", u: "#3d3a48", k: "#1a1820", K: "#26232e" };
export const THORNS = rows(
  24,
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  ".....W.......W......W...",
  ".....w.......w......w...",
  ".W...w..W....w..W...w...",
  ".w...w..w....w..w...w...",
  ".w..ww..w...ww..w..ww...",
  ".ww.wu..ww..wu..ww.wu...",
  ".wu.wu..wu..wu..wu.wu.W.",
  ".wu.wu.Wwu.Wwu..wu.wu.w.",
  ".wu.wu.wwu.wwu.Wwu.wu.w.",
  "uwuuwuuwwuuwwuuwwuuwuuwu",
  "kkkkkkkkkkkkkkkkkkkkkkkk",
  "kKkkkkkKkkkkkkKkkkkkkKkk",
  "kkkkkkkkkkkkkkkkkkkkkkkk",
  "kkkkkkkkkkkkkkkkkkkkkkkk",
  "kkkkkkkkkkkkkkkkkkkkkkkk",
  "kkkkkkkkkkkkkkkkkkkkkkkk",
);
export const WHITE_PALETTE: Palette = { w: "#e7e4dc", W: "#ffffff", s: "#b9b4aa", S: "#cbc6bb", d: "#9a958b" };
export const WHITE_GROUND = rows(
  24,
  "wWwwwwWwwwwwWwwwwwWwwwww",
  "wwwwwwwwwwwwwwwwwwwwwwww",
  "ssssssssdsssssssssdSssss",
  "sSsssssSdsssssSsssdsssss",
  "dddddddddddddddddddddddd",
  "sssdssssssssssdsssssssss",
  "sSsdsssSssssssdssSsssSss",
  "sssdssssssssssdsssssssss",
  "dddddddddddddddddddddddd",
  "ssssssssssdssssssssdssss",
  "sSssssSsssdsssSsssSdssss",
  "ssssssssssdssssssssdssss",
  "dddddddddddddddddddddddd",
  "sssssdssssssssssdsssssss",
  "sSsssdsssSssssssdsssSsss",
  "sssssdssssssssssdsssssss",
  "dddddddddddddddddddddddd",
  "ssssssssdsssssssssdsssss",
  "sSsssssSdsssssSsssdsssss",
  "ssssssssdsssssssssdsssss",
  "dddddddddddddddddddddddd",
  "sssdssssssssssdsssssssss",
  "sSsdsssSssssssdssSsssSss",
  "sssdssssssssssdsssssssss",
);

/* Decorations (drawn on top of tiles). */
export const DECO_PALETTE: Palette = {
  g: "#3f7f6a",
  G: "#78cfa2",
  c: "#3fa9e8",
  C: "#8fe3ff",
  s: "#b8c6d0",
  y: "#ffd27a",
  Y: "#fff3c4",
  w: "#e8e4d8",
  r: "#8a5a34",
  R: "#b0733f",
  b: "#cfc7b4",
  B: "#f0e9d6",
  p: "#7a2f38",
  P: "#a03f4a",
  k: "#221810",
};
export const DECO_GRASS = rows(12, "..G...G.....", ".gG..gG..G..", ".gG.ggG.gG..", "gggggggggg..", "............", "............");
export const DECO_MUSHROOM_SMALL = rows(8, "..CCCC..", ".Cccccc.", "cccccccc", "..ssss..", "...ss...", "...ss...", "..ssss..", "........");
export const DECO_MUSHROOM_TALL = rows(10, "...CCCC...", ".CCccccCC.", "CccccccccC", "cccccccccc", "...sss....", "...sss....", "...sss....", "...sss....", "...sss....", "..sssss...");
export const DECO_CANDLE = rows(6, "..Y...", ".yYy..", ".yyy..", "..w...", "..w...", "..w...", "..w...", ".www..", "......");
export const DECO_CANDELABRA = rows(14, "Y...Y....Y....", "y...y....y....", "w...w....w....", "w...w....w....", "wwwwwwwwwwww..", "......k.......", "......k.......", "......k.......", ".....kkk......", "......k.......", "......k.......", "....kkkkk.....");
export const DECO_SKULL = rows(8, "..BBBB..", ".BbbbbB.", "Bb.bb.bB", "Bbbbbbbb", ".bb.b.b.", "..bbbb..", "........", "........");
export const DECO_BONES = rows(14, "B.....BBBB....", "bBBBBbbbbbB...", "B.....bbbb.B..", "........B.....", "..............", "..............");
export const DECO_CHAIN_HOOK = rows(8, "..rRr...", ".rr.rr..", ".rr.rr..", "..rRr...", "..rr....", "..rr....", ".rrrr...", "........");
export const DECO_BANNER = rows(10, "kkkkkkkkkk", ".PppppppP.", ".PppppppP.", ".PpyyyppP.", ".PppyyppP.", ".PppppppP.", ".PppppppP.", "..PppppP..", "...PppP...", "....PP....");
