import type { SourceAnalysis } from "../types";

/**
 * NARRATIVE ANALYSIS · Lost Garden, episode 1, 0:00 to 1:04.
 *
 * Built from the episode proxy (`12_Episodes/episode-1-proxy.mp4` in the
 * production repository): scene-cut detection plus frames sampled every half
 * second, cross-checked with the subtitle tracks (EN and FR) and the
 * screenplay PDF (`02_Scenario/Episode_1_Scenario.pdf`, page 2). Shot
 * boundaries are exact to about a tenth of a second except where two white
 * shots cut on white, which the detector misses; those are marked `approx`.
 *
 * The screenplay opens on a black screen with Rose's voice; the finished film
 * replaced that black with a white memory (the lily field) and kept a two
 * second black before the sanctuary. The webtoon follows the film.
 */
export const EP1_OPENING_ANALYSIS: SourceAnalysis = {
  source_id: "lost-garden.ep1.0-64",
  title: "Episode 1 · The Awakening of the Lantern Knight · 0:00-1:04",
  origin: {
    kind: "video+screenplay",
    video_url: "https://youtu.be/eZ_JlaLDJ-8",
    screenplay_ref: "Episode_1_Scenario.pdf · FADE IN / INT. SANCTUAIRE SOUTERRAIN, AUTEL DE PIERRE",
    method:
      "Scene-cut detection and 2 fps frame sampling on the 640 px proxy, subtitle tracks for dialogue timing, screenplay for intent.",
  },
  time_start: 0,
  time_end: 63.8,
  shots: [
    {
      shot_id: "s01",
      time_start: 0,
      time_end: 4.4,
      timing: "exact",
      description:
        "White. An overexposed white world, no horizon, a slow wind. Lanterne stands alone in a medium shot, slightly right of centre, facing the camera, arms at his sides. His torn beige cape lifts to the right in the wind; small white petals cross the frame. Colours are washed out, like a memory.",
      characters: ["lanterne"],
      location: "white-lily-field",
      action: "Lanterne stands still, facing forward. Only the cape and the petals move.",
      emotion: "suspended, unreal, quiet",
      shot_type: "medium",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["wind", "low sustained tone"],
      frames: ["/webtoon/ep1-opening/source/t00.jpg"],
      notes: "The desaturation is the meaning: this is not the present.",
    },
    {
      shot_id: "s02",
      time_start: 4.4,
      time_end: 6.3,
      timing: "exact",
      description:
        "Macro on white lilies filling the frame, orange stamens, soft focus at the edges. The only warm colour of the sequence.",
      characters: [],
      location: "white-lily-field",
      action: "Nothing moves but the petals.",
      emotion: "tender, close",
      shot_type: "detail",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["wind"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m05s.jpg"],
    },
    {
      shot_id: "s03",
      time_start: 6.3,
      time_end: 11.2,
      timing: "exact",
      description:
        "Starts fully defocused on white lilies, then the focus pulls to a wide shot: a field of lilies under a white sky. Lanterne stands small at the left, mid-ground, facing right. Far at the right, on a low rise of lilies, a small figure faces him: Rose, in a cloak, pink hair. The distance between them is the subject.",
      characters: ["lanterne", "rose"],
      location: "white-lily-field",
      action: "Rack focus from blur to the two figures facing each other. Neither moves.",
      emotion: "longing, distance",
      shot_type: "extreme_wide",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["wind through lilies"],
      frames: ["/webtoon/ep1-opening/source/t09.jpg"],
      notes: "Geography to keep: Lanterne left, Rose right and slightly higher.",
    },
    {
      shot_id: "s04",
      time_start: 11.2,
      time_end: 12.9,
      timing: "exact",
      description:
        "Big close-up of Rose against the white sky: pink bob hair, the white flower in her hair on the viewer's right, large soft eyes looking straight at the camera, hood down. A petal crosses the frame in the foreground. She is silent.",
      characters: ["rose"],
      location: "white-lily-field",
      action: "Rose looks at Lanterne (at the camera). She does not speak yet.",
      emotion: "calm, watchful",
      shot_type: "close_up",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["wind"],
      frames: ["/webtoon/ep1-opening/source/t11.jpg"],
    },
    {
      shot_id: "s05",
      time_start: 12.9,
      time_end: 13.9,
      timing: "approx",
      description:
        "Detail at ground level: the lace hem of Rose's cream dress and her small feet standing among the white lilies.",
      characters: ["rose"],
      location: "white-lily-field",
      action: "She stands still among the flowers.",
      emotion: "fragile, grounded",
      shot_type: "detail",
      camera_angle: "low",
      dialogue: [],
      sounds: ["wind"],
      frames: ["/webtoon/ep1-opening/source/t13.jpg"],
    },
    {
      shot_id: "s06",
      time_start: 13.9,
      time_end: 16.9,
      timing: "approx",
      description:
        "Extreme wide: a rounded hill entirely covered in white lilies under a white sky. Rose is a speck at the summit; Lanterne a speck at the base, left. Lilies in soft focus in the foreground.",
      characters: ["lanterne", "rose"],
      location: "white-lily-field",
      action: "Both stand still, very far apart.",
      emotion: "immensity, separation",
      shot_type: "extreme_wide",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["wind"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m15s.jpg"],
    },
    {
      shot_id: "s07",
      time_start: 16.9,
      time_end: 20.6,
      timing: "approx",
      description:
        "Medium shot of Rose, waist up, grey-green hooded cloak over the cream dress, lilies around her, white sky. She looks at Lanterne and her lips part: Find me.",
      characters: ["rose"],
      location: "white-lily-field",
      action: "Rose says: Find me.",
      emotion: "tender, a quiet plea",
      shot_type: "medium_close_up",
      camera_angle: "eye_level",
      dialogue: [{ time: 17.9, speaker: "Rose", text: "Find me." }],
      sounds: ["her voice, close and soft"],
      frames: ["/webtoon/ep1-opening/source/t17.jpg"],
      notes: "The only line of the sequence. Lanterne cannot answer; he has no voice.",
    },
    {
      shot_id: "s08",
      time_start: 20.6,
      time_end: 22.6,
      timing: "exact",
      description: "Black. Two full seconds of black and silence.",
      characters: [],
      location: "black",
      action: "Nothing.",
      emotion: "fall, loss",
      shot_type: "void",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["silence"],
      frames: [],
      notes: "Becomes the black gap of the strip: no panel, only distance.",
    },
    {
      shot_id: "s09",
      time_start: 22.6,
      time_end: 25.5,
      timing: "exact",
      description:
        "Extreme wide of the underground sanctuary, blue and black. Pale light falls in beams from high above; twisted black roots frame the left and top; glowing blue mushrooms and pools of light along the floor. Far in the middle distance, tiny, the stone altar with the armour lying on it.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "Nothing moves. The knight lies on the altar, minuscule in the space.",
      emotion: "cold, sacred, held breath",
      shot_type: "extreme_wide",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["cavern reverb", "faint low hum"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m25s.jpg"],
    },
    {
      shot_id: "s10",
      time_start: 25.5,
      time_end: 27.6,
      timing: "exact",
      description:
        "Medium shot: in the foreground a pale translucent larva-like creature, segmented and softly glowing, crawls along a black root. Behind it, out of focus, the altar with Lanterne lying on it, blue light.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "The small creature crawls toward the altar. Lanterne does not move.",
      emotion: "first sign of life, curiosity",
      shot_type: "medium",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["tiny wet clicks"],
      frames: ["/webtoon/ep1-opening/source/t26.jpg"],
      notes: "The screenplay's ghostly small animal; in the film a pale larva.",
    },
    {
      shot_id: "s11",
      time_start: 27.6,
      time_end: 31.3,
      timing: "exact",
      description:
        "Low wide shot along the altar from its foot: the two armoured sabatons rest on the stone lid closest to the camera; above, an immense ornate circular rose window glows cold cyan, ice-like stalactites hanging around it; beams of light fall to the altar.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "Stillness. Light on the lying knight.",
      emotion: "awe, expectation",
      shot_type: "wide",
      camera_angle: "low",
      dialogue: [],
      sounds: ["low hum rising"],
      frames: ["/webtoon/ep1-opening/source/t29.jpg"],
      notes: "The 30 second mark falls inside this shot. The awakening itself starts after it.",
    },
    {
      shot_id: "s12",
      time_start: 31.3,
      time_end: 36.3,
      timing: "exact",
      description:
        "Wide side view of the altar at floor level: the long stone altar runs across the frame, Lanterne lying on it with the helmet to the left and the beige cape hanging over the edge; huge blue mushrooms in the foreground, roots overhead, thin mist.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "Nothing moves. The camera drifts slowly.",
      emotion: "held, sacred",
      shot_type: "wide",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["low hum"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m33s.jpg"],
    },
    {
      shot_id: "s13",
      time_start: 36.3,
      time_end: 39.8,
      timing: "exact",
      description:
        "The rose window fills the frame, seen from below: a great circular tracery glowing cold cyan, stalactites around it, the light growing brighter as if the window woke.",
      characters: [],
      location: "altar-sanctuary",
      action: "The light in the window grows.",
      emotion: "sacred, rising",
      shot_type: "wide",
      camera_angle: "low",
      dialogue: [],
      sounds: ["hum rising"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m38s.jpg"],
    },
    {
      shot_id: "s14",
      time_start: 39.8,
      time_end: 41.3,
      timing: "exact",
      description:
        "High close shot on the lying knight from above the altar: helmet to the right, the two small eye holes, the scarf, the engraved pauldrons, one gauntlet along the body. A first pale beam touches the metal.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "Still. The first light reaches him.",
      emotion: "expectation",
      shot_type: "close_up",
      camera_angle: "high",
      dialogue: [],
      sounds: ["hum"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m40s.jpg"],
    },
    {
      shot_id: "s15",
      time_start: 41.3,
      time_end: 43.8,
      timing: "exact",
      description:
        "Wide from the floor among big glowing mushrooms: the altar far and small in the centre, beams of light now falling hard on it, mist along the ground.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "The beams intensify on the altar.",
      emotion: "the space answers",
      shot_type: "wide",
      camera_angle: "low",
      dialogue: [],
      sounds: ["hum louder"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m42s.jpg"],
    },
    {
      shot_id: "s16",
      time_start: 43.8,
      time_end: 45.5,
      timing: "exact",
      description:
        "Side view along the altar: the whole lying body from the sabatons on the left to the helmet on the right, tall beams of light behind, the cape hanging off the slab.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "Light falls on the whole body.",
      emotion: "suspended",
      shot_type: "full",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["hum"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m44s.jpg"],
    },
    {
      shot_id: "s17",
      time_start: 45.5,
      time_end: 48.3,
      timing: "exact",
      description:
        "Close on the torso: blue light spreads through the armour, the seams of the chest plate and the joints glow cyan, a pauldron dark in the foreground; the glow pulses brighter and brighter.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "The light enters the metal and spreads through the joints.",
      emotion: "the armour comes alive",
      shot_type: "close_up",
      camera_angle: "high",
      dialogue: [],
      sounds: ["crackling hum"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m47s.jpg"],
      notes: "Screenplay: the light spreads in the metal, the joints, the torso, the helmet. The armour trembles.",
    },
    {
      shot_id: "s18",
      time_start: 48.3,
      time_end: 52.0,
      timing: "exact",
      description:
        "Frontal: Lanterne sits up brusquely toward the camera, torso and joints glowing bright cyan, white lilies falling in the foreground; the glow fades as he freezes upright.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "He sits up suddenly, then freezes.",
      emotion: "shock, awakening",
      shot_type: "medium",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["hollow metallic clank", "hum stops"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m50s.jpg"],
      notes: "Screenplay: a small hollow metallic sound, not a voice.",
    },
    {
      shot_id: "s19",
      time_start: 52.0,
      time_end: 54.0,
      timing: "exact",
      description:
        "Frontal medium, sitting on the altar, the glow gone: the hollow helmet turned to the camera, arms down, hands on the stone, mushrooms and roots behind.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "He stays seated, motionless.",
      emotion: "empty, dazed",
      shot_type: "medium",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["silence"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m53s.jpg"],
    },
    {
      shot_id: "s20",
      time_start: 54.0,
      time_end: 56.0,
      timing: "exact",
      description:
        "Black. Two seconds of black.",
      characters: [],
      location: "black",
      action: "Nothing.",
      emotion: "cut, breath",
      shot_type: "void",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["silence"],
      frames: [],
    },
    {
      shot_id: "s21",
      time_start: 56.0,
      time_end: 59.8,
      timing: "exact",
      description:
        "Frontal medium, still seated: he lifts his right gauntlet in front of his chest and looks at it, the helmet tilting toward the hand.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "He raises his right hand and looks at it.",
      emotion: "not understanding",
      shot_type: "medium",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["faint metal creak"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m58s.jpg"],
      notes: "Screenplay: he looks at his hands. He does not understand.",
    },
    {
      shot_id: "s22",
      time_start: 59.8,
      time_end: 63.8,
      timing: "exact",
      description:
        "Side view, close: he bends forward over his knees, the helmet pointing down at his own body, the cape sliding over his back, one gauntlet flat on the stone, the other at his chest.",
      characters: ["lanterne"],
      location: "altar-sanctuary",
      action: "He bends over himself and touches his chest.",
      emotion: "discovery, fear",
      shot_type: "medium_close_up",
      camera_angle: "eye_level",
      dialogue: [],
      sounds: ["metal creak"],
      frames: ["/webtoon/ep1-opening/source/ep1-00m61s.jpg"],
      notes: "Screenplay: he touches his torso, his helmet, his shoulders.",
    },
  ],
  dialogue: [{ time: 17.9, speaker: "Rose", text: "Find me." }],
  sounds: [
    { time: 0, sound: "wind, sustained tone", graphic: false, note: "Atmosphere: served by empty space, not lettering." },
    { time: 17.9, sound: "Rose's voice", graphic: true, note: "A whisper bubble, the only text of the sequence." },
    { time: 20.6, sound: "silence, black", graphic: false, note: "The black gap of the strip and the change of page background." },
    { time: 22.6, sound: "cavern hum", graphic: false, note: "Left silent: the sanctuary must read as silence." },
    { time: 36.3, sound: "hum rising in the window", graphic: true, note: "A rumble SFX under the rose window, larger than at 0:29." },
    { time: 45.5, sound: "crackling light in the metal", graphic: true, note: "A cyan buzzing SFX along the glowing seams." },
    { time: 48.3, sound: "hollow metallic clank", graphic: true, note: "The one hard SFX of the strip, on the sit-up." },
    { time: 54.0, sound: "silence, black", graphic: false, note: "A second black gap, shorter than the first." },
    { time: 56.0, sound: "metal creak", graphic: true, note: "Small soft creaks as he moves for the first time." },
  ],
  continuity: [
    "In the white world every colour is washed out; in the sanctuary the palette is saturated cold blue.",
    "Lanterne is at the left and Rose at the right of the field; Rose stands higher, on the crest.",
    "Rose's flower sits above her left temple, on the viewer's right; her hood is down; her dress is cream with a lace hem.",
    "The rose window is directly above the altar; the altar runs toward the viewer, feet closest to the camera.",
    "No light in the sanctuary other than the beams from above, the window and the mushrooms.",
    "Lanterne emits no light of his own and carries no weapon; his cape is beige with a torn hem.",
    "Exception to the rule above: between 45.5 and 51 the seams and joints of the armour glow cyan while the light enters him; from 52 on he emits nothing again.",
    "On the altar the sabatons point toward the rose window and the helmet toward the foot of the altar; the side views show the helmet on the left when the camera is among the mushrooms and on the right in the high shots.",
    "Once seated he faces the foot of the altar, toward the camera; he never stands before 1:04.",
  ],
};
